# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VoteOnOffice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoteOnOffice
pod 'Firebase', '>= 2.5.0'
pod 'FirebaseUI/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Charts'
  target 'VoteOnOfficeTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Firebase', '>= 2.5.0'
pod 'FirebaseUI/Auth'
pod 'Firebase/Storage'
pod 'Firebase/Firestore'
pod 'Charts'
  end

end
